### ISSUE TITLE
Unable to change number of input boxes

### ISSUE THREAD

**Issue by AntonioLi1** [abdymm/react-native-otp-form#3]
Hi there,
Im trying to make the input only have 4 numbers.
But when i change the number of inputs property to 4, it doesnt change. 
What would be the fix?

**Comment by abdymm** [comment]
> Hi there, Im trying to make the input only have 4 numbers. But when i change the number of inputs property to 4, it doesnt change. What would be the fix?

hang on, let me check!

**Comment by abdymm** [comment]
> > Hi there, Im trying to make the input only have 4 numbers. But when i change the number of inputs property to 4, it doesnt change. What would be the fix?

hi, it work on my end, have you tried reload your app?

<img width="323" alt="Screenshot 2022-11-30 at 08 00 36" src="https://user-images.githubusercontent.com/1695466/204681963-5e54ae97-5a6b-4915-bd29-2706843a6921.png">

**Comment by abdymm** [comment]
hey  @AntonioLi1 is the issue still exist?

**Comment by AntonioLi1** [comment]
I switched to another package.
But thank you for responding so quickly!

**Comment by abdymm** [comment]
> I switched to another package. But thank you for responding so quickly!

oh okay, will close this issue then, good luck!
